const officialProductsUrl = "https://www.heromotocorp.com/en-in/products.html";

const product = (data) => ({
  sourceUrl: officialProductsUrl,
  ...data,
  image: `hero-catalog-normalized/${data.image
    .split("/")
    .pop()
    .replace(/\.[^.]+$/, ".webp")}`,
});

// Current model names, engine capacities and imagery were verified against
// Hero MotoCorp's India catalogue on 10 September 2026. Local stock, colours,
// variants and prices are deliberately confirmed by the showroom at enquiry.
export const catalogProducts = [
  product({
    id: "xtreme-250r",
    name: "Hero Xtreme 250R",
    type: "Motorcycle",
    segment: "New launch",
    engine: "250 cc",
    intent: "Performance",
    image: "hero-catalog/xtreme-250r.webp",
    featured: true,
  }),
  product({
    id: "xpulse-210",
    name: "Hero Xpulse 210",
    type: "Motorcycle",
    segment: "New launch",
    engine: "210 cc",
    intent: "Adventure",
    image: "hero-catalog/xpulse-210.webp",
    featured: true,
  }),
  product({
    id: "splendor-plus-xtec-2-0",
    name: "Hero Splendor+ XTEC 2.0",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Daily commute",
    image: "hero-catalog/splendor-plus-xtec-2.webp",
  }),
  product({
    id: "splendor-plus",
    name: "Hero Splendor+",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Daily commute",
    image: "hero-catalog/splendor-plus.webp",
    featured: true,
  }),
  product({
    id: "splendor-plus-xtec",
    name: "Hero Splendor+ XTEC",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Daily commute",
    image: "hero-catalog/splendor-plus-xtec.webp",
  }),
  product({
    id: "hf-deluxe",
    name: "Hero HF Deluxe",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Value commute",
    image: "hero-catalog/hf-deluxe.webp",
  }),
  product({
    id: "hf-100",
    name: "Hero HF 100",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Value commute",
    image: "hero-catalog/hf-100.webp",
  }),
  product({
    id: "glamour-x",
    name: "Hero Glamour X",
    type: "Motorcycle",
    segment: "125 cc",
    engine: "125 cc",
    intent: "Smart commute",
    image: "hero-catalog/glamour-x.webp",
  }),
  product({
    id: "xtreme-125r",
    name: "Hero Xtreme 125R",
    type: "Motorcycle",
    segment: "125 cc",
    engine: "125 cc",
    intent: "Sporty commute",
    image: "hero-catalog/xtreme-125r.webp",
  }),
  product({
    id: "glamour",
    name: "Hero Glamour",
    type: "Motorcycle",
    segment: "125 cc",
    engine: "125 cc",
    intent: "Daily commute",
    image: "hero-catalog/glamour.webp",
  }),
  product({
    id: "super-splendor-xtec",
    name: "Hero Super Splendor XTEC",
    type: "Motorcycle",
    segment: "125 cc",
    engine: "124.7 cc",
    intent: "Family commute",
    image: "hero-catalog/super-splendor-xtec.webp",
  }),
  product({
    id: "xtreme-160r-4v",
    name: "Hero Xtreme 160R 4V",
    type: "Motorcycle",
    segment: "Premium",
    engine: "163.2 cc",
    intent: "Performance",
    image: "hero-catalog/xtreme-160r-4v.webp",
  }),
  product({
    id: "xtreme-160r",
    name: "Hero Xtreme 160R",
    type: "Motorcycle",
    segment: "Premium",
    engine: "163.2 cc",
    intent: "Performance",
    image: "hero-catalog/xtreme-160r.webp",
  }),
  product({
    id: "xpulse-200-4v",
    name: "Hero Xpulse 200 4V",
    type: "Motorcycle",
    segment: "Premium",
    engine: "199.6 cc",
    intent: "Adventure",
    image: "hero-catalog/xpulse-200-4v.webp",
  }),
  product({
    id: "karizma-xmr",
    name: "Hero Karizma XMR",
    type: "Motorcycle",
    segment: "Premium",
    engine: "210 cc",
    intent: "Sport touring",
    image: "hero-catalog/karizma-xmr.webp",
  }),
  product({
    id: "harley-x440",
    name: "Harley-Davidson X440",
    type: "Motorcycle",
    segment: "Premia",
    engine: "440 cc",
    intent: "Premium roadster",
    image: "hero-catalog/harley-x440.webp",
  }),
  product({
    id: "splendor-plus-flex",
    name: "Hero Splendor+ Flex",
    type: "Motorcycle",
    segment: "New launch",
    engine: "97.2 cc",
    intent: "Flex-fuel commute",
    image: "hero-catalog/splendor-plus-flex.png",
  }),
  product({
    id: "hf-deluxe-flex",
    name: "Hero HF Deluxe Flex",
    type: "Motorcycle",
    segment: "New launch",
    engine: "97.2 cc",
    intent: "Flex-fuel commute",
    image: "hero-catalog/hf-deluxe-flex.png",
  }),
  product({
    id: "passion-plus",
    name: "Hero Passion+",
    type: "Motorcycle",
    segment: "100 cc",
    engine: "97.2 cc",
    intent: "Daily commute",
    image: "hero-catalog/passion-plus.webp",
  }),
  product({
    id: "super-splendor-xtec-2-0",
    name: "Hero Super Splendor XTEC 2.0",
    type: "Motorcycle",
    segment: "New launch",
    engine: "124.7 cc",
    intent: "Family commute",
    image: "hero-catalog/super-splendor-xtec-2.png",
  }),
  product({
    id: "harley-davidson-x440-t",
    name: "Harley-Davidson X440 T",
    type: "Motorcycle",
    segment: "New launch",
    engine: "440 cc",
    intent: "Premium roadster",
    image: "hero-catalog/harley-x440-t.webp",
  }),
  product({
    id: "destini-110",
    name: "Hero Destini 110",
    type: "Scooter",
    segment: "Scooter",
    engine: "110 cc",
    intent: "Family scooter",
    image: "hero-catalog/destini-110.webp",
  }),
  product({
    id: "destini-125",
    name: "Hero Destini 125",
    type: "Scooter",
    segment: "Scooter",
    engine: "125 cc",
    intent: "Family scooter",
    image: "hero-catalog/destini-125.svg",
    featured: true,
  }),
  product({
    id: "xoom-160",
    name: "Hero Xoom 160",
    type: "Scooter",
    segment: "Premia",
    engine: "156 cc",
    intent: "Premium scooter",
    image: "hero-catalog/xoom-160.webp",
  }),
  product({
    id: "xoom-125",
    name: "Hero Xoom 125",
    type: "Scooter",
    segment: "Scooter",
    engine: "124.6 cc",
    intent: "Sporty scooter",
    image: "hero-catalog/xoom-125.webp",
  }),
  product({
    id: "destini-prime",
    name: "Hero Destini Prime",
    type: "Scooter",
    segment: "Scooter",
    engine: "124.6 cc",
    intent: "Family scooter",
    image: "hero-catalog/destini-prime.webp",
  }),
  product({
    id: "xoom-110",
    name: "Hero Xoom 110",
    type: "Scooter",
    segment: "Scooter",
    engine: "110.9 cc",
    intent: "City scooter",
    image: "hero-catalog/xoom-110.webp",
  }),
  product({
    id: "pleasure-plus-xtec",
    name: "Hero Pleasure+ XTEC",
    type: "Scooter",
    segment: "Scooter",
    engine: "110.9 cc",
    intent: "City scooter",
    image: "hero-catalog/pleasure-plus-xtec.webp",
  }),
  product({
    id: "vida-v2-plus",
    name: "VIDA V2 Plus",
    type: "Electric",
    segment: "Electric",
    engine: "143 km IDC",
    specLabel: "Claimed range",
    intent: "Electric commute",
    image: "hero-catalog/vida-v2-plus.webp",
    sourceUrl: "https://www.vidaworld.com/",
  }),
];

export const featuredProducts = catalogProducts.filter((item) => item.featured);

export const catalogMeta = {
  count: catalogProducts.length,
  sourceLabel: "Hero MotoCorp official India catalogue",
  sourceUrl: officialProductsUrl,
  verifiedOn: "10 September 2026",
  priceNote:
    "On-road price, finance, colour and availability vary by model and are confirmed by Ashok Hero.",
};
